# Generated by Django 5.2.4 on 2025-07-29 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_user_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='usrename',
            new_name='username',
        ),
    ]
