# Generated by Django 5.2.4 on 2025-07-15 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friend',
            new_name='login',
        ),
    ]
